### PR TITLE
[#83452334] remove width/height round

### PR DESCRIPTION
**Pull request by FangAtKabam**
Our sidebar image aspect ratio is 146/80 = 1.825. There's a edge case that during the resize, if cropped image aspect ratio is smaller than [the aspect ratio we set on the server](https://github.com/Kabam/gatsby/pull/122/files#diff-ea991fa1cd44e0c51311a5a2d2b18aa9R22), then RMagick fails to crop the image since we are using resize_to_fill, I should change it to resize_to_fit.

so remove rounding the number.

### CODE REVIEW

**Comment by jaygeeseman** [comment]
Can you explain a little more? How does removing rounding affect rmagick? resize_to_fill should change the aspect ratio if needed. It sounds like it has the possibility of being 1 pixel off, so a 1 pixel change to aspect ratio should be okay.

**Comment by FangAtKabam** [comment]
during the resize, there was one time I cropped the image size to be 537, 295, and that gives aspect ratio around 1.820, and resize_to_fill stop producing the image. I manually test the dimension again with 538, 295 which works fine. so removing rounding here to eliminate the edge case like this.

**Comment by jaygeeseman** [comment]
I don't think that's going to fix the problem. We shouldn't care what RMagick's resizing implementation is, but rather change the way we use it to work for whatever we send.

What happens if you use resize_to_fill and only specify the image width? In my past experience with ImageMagick, I think that is how it's meant to be used.

**Comment by FangAtKabam** [comment]
tried uploaded an image with crop size [537, 295], and use resize_to_fill without specifying the height, it still doesn't resize the image. but resize_to_fit works. I don't really understand the reason.

**Comment by FangAtKabam** [comment]
close this PR, need to have some more digging on how resize_to_fill works.

**Pull request closed without merging**
